Update CLI to the newest function CRD
kyma-project/cli pull request #1435
Opened 2022-11-04 10:26 UTC by Cortey

**Description**
Updated CLI to support the newest versions:
- serverless.kyma-project.io/v1alpha2
- gateway.kyma-project.io/v1beta1

**Related issue(s)**
https://github.com/kyma-project/cli/issues/1314

2022-11-07 08:18 UTC, Cortey commented
/retest

2022-11-07 08:34 UTC, clebs approved these changes

2022-11-07 09:35 UTC, Cortey commented
/retest

2022-11-07 09:46 UTC, Cortey commented
/retest

2022-11-07 13:36 UTC, Cortey commented
/retest

2022-11-07 14:18 UTC, Cortey commented
Waits for https://github.com/kyma-project/hydroform/pull/388

2022-11-08 10:44 UTC, Cortey commented
/retest

2022-11-09 11:59 UTC, Cortey commented
/retest

2022-11-09 12:39 UTC, clebs requested changes

2022-11-09 12:39 UTC, clebs commented on go.mod
> +	github.com/kyma-incubator/reconciler v0.0.0-20221102095238-a3b6df7d2e27
Please revert this line, the reconciler is being downgraded.

2022-11-09 13:05 UTC, Cortey commented
/retest

2022-11-09 13:06 UTC, merged