Add new API subscription version
kyma-project/cli pull request #1542
Opened 2023-02-17 14:02 UTC by MichalKalke

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-02-28 13:05 UTC, MichalKalke commented
/test all

2023-02-28 14:06 UTC, grego952 submitted a review, later dismissed

2023-03-01 14:14 UTC, kwiatekus requested changes
I'd rather see this flag not using camel case format but 
`--schema-version`

I cant use the flag when calling kyma init commang
```bash
../bin/kyma-darwin init function --schemaVersion v1                                                                                        
Error: unknown flag: --schemaVersion
```

I also dont see it when calling `kyma init function --help`

2023-03-02 10:11 UTC, MichalKalke commented
> I'd rather see this flag not using camel case format but `--schema-version`
> 
> I cant use the flag when calling kyma init commang
> 
> ```shell
> ../bin/kyma-darwin init function --schemaVersion v1                                                                                        
> Error: unknown flag: --schemaVersion
> ```
> 
> I also dont see it when calling `kyma init function --help`

I have changed the flag to `schema-version` as you suggested.
I have also added above mentioned flag to the `kyma init function`.

2023-03-02 10:15 UTC, grego952 submitted a review, later dismissed

2023-03-02 11:23 UTC, kwiatekus submitted a review, later dismissed

2023-03-06 08:28 UTC, MichalKalke commented
/test all

2023-03-06 08:42 UTC, MichalKalke commented
/retest

2023-03-06 09:04 UTC, grego952 approved these changes

2023-03-06 09:09 UTC, kwiatekus approved these changes

2023-03-07 08:49 UTC, jakobmoellersap approved these changes

2023-03-07 08:49 UTC, merged