Add custom resource policy flag to the enable module command
kyma-project/cli pull request #1584
Opened 2023-03-10 13:38 UTC by nesmabadr

**Description**

Changes proposed in this pull request:

- Add `policy` flag to `enable module` command to manage the custom resource policy.
- Update channel and policy for already existing modules.

**Related issue(s)**
`Fixes #1582 `

2023-03-10 13:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/cli?pullRequest=1584) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/cli?pullRequest=1584) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/cli?pullRequest=1584) it.</sub>

2023-03-10 13:56 UTC, lindnerby approved these changes
lgtm, waiting for tws

2023-03-10 14:18 UTC, nataliasitko commented on docs/gen-docs/kyma_alpha_enable_module.md
> +  -p, --policy string      Determines how the module is managed, either install or ignore the default values provided in the module template. Available values are 'CreateAndDelete' or 'Ignore'. (defa
```suggestion
  -p, --policy string      Determines how the module is managed. Use 'CreateAndDelete' to install the default values provided in the module template or 'Ignore' to ignore them. (default "CreateAndDelete")
```

2023-03-10 14:25 UTC, nesmabadr commented on docs/gen-docs/kyma_alpha_enable_module.md
> +  -p, --policy string      Determines how the module is managed, either install or ignore the default values provided in the module template. Available values are 'CreateAndDelete' or 'Ignore'. (defa
Changed.

2023-03-13 07:15 UTC, lindnerby commented on cmd/kyma/alpha/enable/module/opts.go
> +	CustomResourcePolicyCreateAndDelete = "CreateAndDelete"
Since these consts are not used outside of it (for now), I guess they can be package-private.

2023-03-13 09:11 UTC, nataliasitko approved these changes

2023-03-13 11:13 UTC, jakobmoellersap requested changes
Mini-Nit, other than that LGTM :) Also needs TW review after that change again

2023-03-13 11:13 UTC, jakobmoellersap commented on cmd/kyma/alpha/enable/module/opts.go
> +	customResourcePolicyCreateAndDelete = "CreateAndDelete"
can you reference the existing v1beta1 API from lifecycle manager here? Its included as an in-code dependency already.

2023-03-14 05:53 UTC, lindnerby approved these changes

2023-03-14 08:49 UTC, jakobmoellersap approved these changes

2023-03-14 08:59 UTC, nataliasitko approved these changes

2023-03-14 09:00 UTC, merged