New version notifier
kyma-project/cli pull request #1611
Opened 2023-03-29 10:30 UTC by amritanshusikdar

**Description**
User gets notified if using an old version of the CLI with a warning to upgrade to a newer version.

**Related issue(s)**

Resolves #1312

2023-03-29 10:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/cli?pullRequest=1611) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/cli?pullRequest=1611) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/cli?pullRequest=1611) it.</sub>

2023-03-31 14:06 UTC, lindnerby commented
/retest-required

2023-04-04 07:03 UTC, lindnerby requested changes

2023-04-04 07:03 UTC, lindnerby commented on cmd/kyma/version/checker.go
> +		nicePrint.PrintImportantf("CAUTION: You're using an outdated version of the Kyma CLI. The latest stable version is: %s", stableCLINumber)
Please print the current version as well

2023-04-04 07:03 UTC, lindnerby commented on cmd/kyma/version/checker.go
> +
Let's return if any value required for the condition check is empty, although it's very unlikely to happen

2023-04-04 07:03 UTC, lindnerby commented on cmd/kyma/version/checker.go
> +	if info, ok := debug.ReadBuildInfo(); ok {
Let's early return if `!ok`

2023-04-04 09:23 UTC, amritanshusikdar commented on cmd/kyma/version/checker.go
> +type KymaCLIMetadata struct {
Going ahead with `LatestGitTag`

2023-04-04 09:28 UTC, amritanshusikdar commented on cmd/kyma/version/checker.go
> +	//	and don't disrupt the usual CLI Flow
done

2023-04-13 06:26 UTC, lindnerby requested changes

2023-04-13 06:26 UTC, lindnerby commented on cmd/kyma/version/checker.go
> +	GitHubAPIEndpoint = "https://api.github.com/repos/kyma-project/cli/releases/latest"
Can be pkg-private

2023-04-13 06:26 UTC, lindnerby commented on cmd/kyma/version/checker.go
> +type LatestGitTag struct {
Can be pkg-private

2023-04-13 06:26 UTC, lindnerby commented on cmd/kyma/version/checker.go
> +package version
Probably not the fitting pkg for this function. Can we move it to somewhere internal?

2023-04-13 06:26 UTC, lindnerby commented on cmd/kyma/version/checker.go
> +	if err != nil {
```suggestion
	if err != nil || !matched {
```

2023-04-13 06:26 UTC, lindnerby commented on cmd/kyma/version/checker.go
> +	if err != nil {
Let's semantically group the check here

2023-04-13 12:06 UTC, lindnerby approved these changes

2023-04-13 12:17 UTC, mmitoraj approved these changes

2023-04-13 12:18 UTC, merged