Add option to override default namespace
kyma-project/cli pull request #1749
Opened 2023-08-25 14:37 UTC by nesmabadr

**Description**

Changes proposed in this pull request:

- Add the option to override the namespace using the config file with the Create Module command

**Related issue(s)**
Resolves #1727

2023-08-28 08:36 UTC, lindnerby requested changes

2023-08-28 08:36 UTC, lindnerby commented on cmd/kyma/alpha/create/module/moduleconfig.go
> +	namespaceMaxLen   = 253
Let's be consistent and extract the namespace regex pattern below as well into const?

2023-08-28 08:36 UTC, lindnerby commented on pkg/module/template.go
> +func Template(remote ocm.ComponentVersionAccess, moduleTemplateName, namespace string, channel string, data []byte, labels, annotations map[string]string) ([]byte, error) {
Can we start to create some unit tests for this func? Should be nice and easy to make it table driven?

2023-08-28 09:45 UTC, lindnerby requested changes

2023-08-28 09:45 UTC, lindnerby commented on cmd/kyma/alpha/create/module/module.go
> +const kcpSystemNamespace = "kcp-system"
I think also need to provide the namespace flag to the cmd itself right? And there you can set the default value

2023-08-29 05:28 UTC, mmitoraj approved these changes

2023-08-29 05:28 UTC, merged