fix: Remove CustomStateCheck flags from the Module Command
kyma-project/cli pull request #1767
Opened 2023-09-12 12:55 UTC by LeelaChacha

Closes #1729

2023-09-15 07:51 UTC, mmitoraj approved these changes

2023-09-15 08:13 UTC, ruanxin commented on cmd/kyma/alpha/create/module/moduleconfig_test.go
> +			wantErr: false,
This should have error returned, a proper custom state should have at least one `Ready` and one `Error` mapped.

2023-09-15 08:19 UTC, ruanxin requested changes
have a problem on the validation logic

2023-09-15 08:43 UTC, lindnerby commented
> have a problem on the validation logic

Will take a look

2023-09-19 11:13 UTC, ruanxin approved these changes

2023-09-19 11:53 UTC, merged