Enrich installation guide
kyma-project/cli pull request #638
Opened 2020-11-05 15:20 UTC by shorim

**Description**

Changes proposed in this pull request:

- add examples for using custom components and custom overrides when installing Kyma
- change test data used for overrides, since current overrides are not applicable after `istio` upgrade to 1.6

**Related issue(s)**

#610

2020-11-06 08:20 UTC, a-thaler commented on docs/03-02-examples.md
> +
Maybe add a remark that you can have multiple configmaps for different components in the same file and that you can repeat the "-o" flag with different files. Please use the full name of flags in docu like "--override"

2020-11-06 08:21 UTC, a-thaler commented on docs/03-02-examples.md
That is a veryy good starting point and is what we need. Please extend it more with other examples regarding the --source flag and custom domains

2020-11-11 06:32 UTC, alexandra-simeonova commented on docs/03-02-examples.md
> +- For example, if your `{IMAGE}` is `user/my-kyma-installer:v1.4.0`, then this command will build an image from your local sources and push it your repository `user/my-kyma-installer` with the tag `v
```suggestion
- For example, if your `{IMAGE}` is `user/my-kyma-installer:v1.4.0`, then this command will build an image from your local sources and push it your repository `user/my-kyma-installer` with the tag `v1.4.0`. Then, this image `user/my-kyma-installer:v1.4.0` will be used in the Deployment for `kyma-installer`.
```

2020-11-11 06:32 UTC, alexandra-simeonova commented on docs/03-02-examples.md
> +To install kyma with only specific components, run:
```suggestion
To install Kyma with only specific components, run:
```

2020-11-11 06:32 UTC, alexandra-simeonova commented on docs/03-02-examples.md
> +- It is also possible to provide multiple override files at the same time
```suggestion
- It is also possible to provide multiple override files at the same time:
```

2020-11-11 09:40 UTC, suleymanakbas91 approved these changes

2020-11-11 09:45 UTC, suleymanakbas91 requested changes
Whatever written in the install Kyma part is also applicable for the upgrade. How about we use install/upgrade everywhere in this part instead of only install? Does it make sense? Otherwise, we would need another part for the upgrade. @a-thaler @shorim

2020-11-11 10:24 UTC, a-thaler commented
Yes, I'm fine with combining it.

2020-11-12 13:59 UTC, suleymanakbas91 approved these changes

2020-11-12 14:06 UTC, shorim commented
/test pre-kyma-cli-integration

2020-11-12 14:08 UTC, alexandra-simeonova approved these changes

2020-11-12 14:33 UTC, merged