Add alpha installation commands
kyma-project/cli pull request #661
Opened 2020-11-26 14:26 UTC by suleymanakbas91

**Description**

Changes proposed in this pull request:

- Add alpha installation commands

**Related issue(s)**

See https://github.com/kyma-project/kyma/issues/9347

2020-11-27 13:37 UTC, suleymanakbas91 commented
/retest

2020-11-30 08:43 UTC, clebs approved these changes

2020-11-30 11:55 UTC, alexandra-simeonova requested changes

2020-11-30 11:55 UTC, alexandra-simeonova commented on cmd/kyma/alpha/cmd.go
> +		Short: "Executes the commands in alpha testing stage.",
```suggestion
		Short: "Executes the commands in alpha testing stage.",
		Long:  "Use this command to execute commands in alpha testing stage.",
```
In other docs, there is always a description starting with "Use this command..." and on the preview the same text is shown twice:

<img width="400" alt="Screen Shot 2020-11-30 at 12 44 10" src="https://user-images.githubusercontent.com/49867570/100606818-48dc0380-330a-11eb-86b1-75f31ab10d88.png">

So I wanted to re-word it somehow.

2020-11-30 11:55 UTC, alexandra-simeonova commented on cmd/kyma/alpha/uninstall/cmd.go
> +		Long:    `Use this command to uninstall Kyma on a running Kubernetes cluster.`,
```suggestion
		Short:   "Uninstalls Kyma from a running Kubernetes cluster.",
		Long:    `Use this command to uninstall Kyma from a running Kubernetes cluster.`,
```

2020-11-30 12:59 UTC, alexandra-simeonova approved these changes

2020-11-30 13:02 UTC, clebs approved these changes

2020-11-30 13:17 UTC, merged