Adapt (inline-)doc regards to new Hydroform branch-install-feature
kyma-project/cli pull request #849
Opened 2021-04-12 11:49 UTC by JeremyHarisch

**Description**

Changes proposed in this pull request:

- Adapted Docs and Inline-Docs regards [new feature in Hydroform.](https://github.com/kyma-project/hydroform/pull/239)

2021-04-12 12:43 UTC, clebs submitted a review, later dismissed

2021-04-19 07:27 UTC, skhalash requested changes

2021-04-19 07:27 UTC, skhalash commented on cmd/kyma/upgrade/cmd.go
> +	- To use a specific branch (e.g. main-branch), write "kyma install --source=main".
```suggestion
	- To use a specific branch (e.g. main branch), write "kyma install --source=my-branch-name".
```

2021-04-19 07:27 UTC, skhalash commented on cmd/kyma/install/cmd.go
> +	- To use a specific branch (e.g. main-branch), write "kyma install --source=main".
```suggestion
	- To use a specific branch (e.g. main branch), write "kyma install --source=my-branch-name".
```

2021-04-19 07:27 UTC, skhalash commented on docs/gen-docs/kyma_install.md
> +                               	- To use a specific branch (e.g. main-branch), write "kyma install --source=main".
```suggestion
                               	- To use a specific branch (e.g. main branch), write "kyma install --source=my-branch-name".
```

2021-04-19 07:27 UTC, skhalash commented on docs/gen-docs/kyma_upgrade.md
> +                               	- To use a specific branch (e.g. main-branch), write "kyma install --source=main".
```suggestion
                               	- To use a specific branch (e.g. main branch), write "kyma install --source=my-branch-name".
```

2021-04-19 07:35 UTC, skhalash approved these changes

2021-04-19 08:19 UTC, NHingerl commented on cmd/kyma/install/cmd.go
> +	- To use a specific branch (e.g. main branch), write "kyma install --source=my-branch-name".
```suggestion
	- To use a specific branch (e.g. main branch), write "kyma install --source=<my-branch-name>".
```

As it's a placeholder, let's use brackets

2021-04-19 08:20 UTC, NHingerl commented on cmd/kyma/upgrade/cmd.go
> +	- To use a specific branch (e.g. main branch), write "kyma install --source=my-branch-name".
```suggestion
	- To use a specific branch (e.g. main branch), write "kyma install --source=<my-branch-name>".
```

2021-04-19 08:26 UTC, NHingerl approved these changes

2021-04-19 09:01 UTC, NHingerl approved these changes

2021-04-19 09:23 UTC, skhalash approved these changes

2021-04-19 09:29 UTC, alexandra-simeonova approved these changes

2021-04-19 09:30 UTC, merged