Fix certificate import (#853)
kyma-project/cli pull request #855
Opened 2021-04-14 14:51 UTC by suleymanakbas91

**Description**

Changes proposed in this pull request:

- Make certificate import work for both alpha and existing way of installation.

2021-04-14 15:34 UTC, tobiscr approved these changes

2021-04-15 07:24 UTC, clebs commented on internal/trust/trust_darwin.go
> +	return "1. Download the certificate: kubectl get secret kyma-gateway-certs -n istio-system -o jsonpath='{.data.cert}' > kyma.crt\n" +
This step is for the new installation right? In the old installation the cert is still in a configmap in `kyma-system` right?
From the git history, the old instructions were:
`kubectl get configmap net-global-overrides -n kyma-installer -o jsonpath='{.data.global\\.ingress\\.tlsCrt}' | base64 --decode > kyma.crt`

2021-04-15 07:26 UTC, clebs commented on internal/trust/trust_windows.go
> +		"2. Download the certificate: kubectl get secret kyma-gateway-certs -n istio-system -o jsonpath='{.data.cert}' > tmp.txt\n" +
Same issue as above, wrong kubectl command on instructions

2021-04-15 07:27 UTC, clebs commented on internal/trust/trust_linux.go
> +	return "1. Download the certificate: kubectl get secret kyma-gateway-certs -n istio-system -o jsonpath='{.data.cert}' > kyma.crt\n" +
Same issue as above, wrong kubectl command on instructions

2021-04-15 07:28 UTC, clebs requested changes
Instructions kubectl commands for old installation are incorrect.

2021-04-15 08:10 UTC, clebs approved these changes

2021-04-15 08:17 UTC, merged