Add flag for custom port mapping in K3D
kyma-project/cli pull request #943
Opened 2021-07-16 11:18 UTC by elchead

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2021-07-16 15:04 UTC, skhalash requested changes
I have a small comment. There is an unspoken convention in many CLIs about how to express port mapping. For example:
* [docker](https://docs.docker.com/engine/reference/run/#expose-incoming-ports)
* [kubectl port-forward] (https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#port-forward)
* [k3d](https://k3d.io/usage/commands/k3d_cluster_create/)

It's always `LOCAL_PORT:REMOTE_PORT`, not `LOCAL_PORT=REMOTE_PORT` and not `REMOTE_PORT=LOCAL_PORT`. If there are multiple ports to map, usually the same flag is used multiple times (the way `docker run` or `k3d create cluster` does it). I'd also avoid using the word `map` in the flag, because the above mentioned format already makes it clear that port mapping is involved.

Long story short, I'd rather use the same format all the other CLIs use in order not to confuse the users:
```bash
kyma alpha provision k3s --name k3s --port 8000:80 --port 8443:443
```
or even pass ports to k3s as is together with @nodefilter

```bash
kyma alpha provision k3s --name k3s --port 8000:80@loadbalancer --port 8443:443@loadbalancer
```

2021-07-19 07:56 UTC, NHingerl commented on cmd/kyma/alpha/provision/k3s/cmd.go
>  	cmd.Flags().StringVarP(&o.KubernetesVersion, "kube-version", "k", "1.20.7", "Kubernetes version of the cluster.")
```suggestion
	cmd.Flags().StringVarP(&o.KubernetesVersion, "kube-version", "k", "1.20.7", "Kubernetes version of the cluster")
```

2021-07-20 09:15 UTC, NHingerl approved these changes

2021-07-20 09:36 UTC, skhalash approved these changes

2021-07-20 09:38 UTC, merged